# Generated by Django 5.1.1 on 2024-12-07 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAP_App', '0004_forumcategory_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='foto_perfil',
            field=models.ImageField(default='perfil/default.jpg', upload_to='perfil/'),
        ),
        migrations.AlterField(
            model_name='adoptioncenter',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='adoptioncenter',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='adoptioncenter',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='veterinaryclinic',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='veterinaryclinic',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='veterinaryclinic',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
